version: "3.8"

services:
  db:
    image: postgres:14.5
    container_name: spring-template-postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-template
    restart: "no"