spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
    url: jdbc:postgresql://localhost:5430/spring-template
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082